spring:
  application:
    name: spring-redis

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 5m

  datasource:
    url: jdbc:mysql://localhost:3306/redis_example_app?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true